# Basic Linear Algebra

In [11]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 3  4  1
 3  4  3
 3  3  1

In [2]:
B = A
C = copy(A)
[ B C]

3×6 Matrix{Int64}:
 3  2  1  3  2  1
 1  2  3  1  2  3
 1  2  3  1  2  3

In [3]:
A[1] = 17
[B C]

3×6 Matrix{Int64}:
 17  2  1  3  2  1
  1  2  3  1  2  3
  1  2  3  1  2  3

In [12]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

### Multiplication

In [13]:
b = A * x

3-element Vector{Float64}:
  8.0
 10.0
  7.0

### Transpose
`A'` is the conjugate transpose, whereas `A.'` is just the transpose

In [6]:
A_symm = A + A'

3×3 Matrix{Int64}:
 34  3  2
  3  4  5
  2  5  6

### Transposed multiplication
Julia allows us to write this without using `*`

In [7]:
Apd = A'A

3×3 Matrix{Int64}:
 291  38  23
  38  12  14
  23  14  19

### Solving linear systems
The problem $Ax = b$ for a square matrix $A$ is solved by `\` function

In [14]:
A \ b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

### Overdetermined system
When $A$ is tall, the `\` function calculates the least squares solution.

In [15]:
A_tall = A[:, 1:2]
display(A_tall)

3×2 Matrix{Int64}:
 3  4
 3  4
 3  3

In [16]:
A_tall\b

2-element Vector{Float64}:
 0.33333333333333787
 1.9999999999999964

The `\` function also works for rank-deficit least squares problems. In this case, the least squares solution is not unique and Julia returns the solution with smallest form.

In [17]:
A = randn(3, 3)

3×3 Matrix{Float64}:
  0.10988  -1.98483   -0.333585
  1.14302   0.135921  -0.529341
 -1.44216   1.62791   -2.22209

In [18]:
[A[:, 1] A[:, 1]]\b

2-element Vector{Float64}:
 0.32575732961350695
 0.32575732961350695

### Underdetermined system
When $A$ is short, the `\` function calculates the minimum norm solution

In [19]:
A_short = A[1:2, :]
display(A_short)
A_short\b[1:2]

2×3 Matrix{Float64}:
 0.10988  -1.98483   -0.333585
 1.14302   0.135921  -0.529341

3-element Vector{Float64}:
  7.287499327905749
 -2.968718850760486
 -3.917579190954642